### ISSUE TITLE
[feat] Styling index.html

### ISSUE THREAD

**Issue by wrexrus** [SooryaCodes/HACKTOBERFEST-2024-CHALLENGE#3]
Would like to style the home page by giving more css, hovering effect and different styles

![image](https://github.com/user-attachments/assets/001f9b05-fa69-48d7-9281-af30d7d8238e)

Please assign me this issue under hacktoberfest

**Comment by wrexrus** [comment]
add labels hacktoberfest-accepted

**Comment by SooryaCodes** [comment]
Yes, you can add more styles and effects.

**Comment by wrexrus** [comment]
why did u close this issue i wanted to work

**Comment by wrexrus** [comment]
Please review my new PR 
#4 
add the label also
